# theme settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

# site settings
locale: "en-US"
title: "monkeyspace"
subtitle: "a space for monkey"
name: "noah"
description: we'll see if this goes anywhere...
repository: "lingawakad/lingawakad.github.io"
show_date: true
enable_copy_code_button: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

plugins:
- jekyll-feed
- jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
